"""Trivia question bank for YouBelong's Games Hub.

Curated, family-friendly, evergreen questions across all required categories.
Each question is tagged with a difficulty so the game can pick from the right
pool — easy / moderate / hard / nightmare.

Schema: { id, category, difficulty, q, choices, answer, explain }
"""

CATEGORIES = [
    "Australia",
    "History",
    "Music",
    "Movies",
    "Sport",
    "Gardening",
    "General Knowledge",
]
DIFFICULTIES = ["easy", "moderate", "hard", "nightmare"]


def _q(id, category, difficulty, q, choices, answer, explain=""):
    return {"id": id, "category": category, "difficulty": difficulty, "q": q,
            "choices": choices, "answer": answer, "explain": explain}


QUESTIONS = [
    # ---------------------------- AUSTRALIA ----------------------------
    _q("aus-e-01", "Australia", "easy", "What is the capital city of Australia?",
       ["Sydney", "Canberra", "Melbourne", "Brisbane"], 1,
       "Canberra was chosen as a compromise between Sydney and Melbourne."),
    _q("aus-e-02", "Australia", "easy", "Which famous rock is in the centre of Australia?",
       ["Uluru", "Kata Tjuta", "Mount Augustus", "Wave Rock"], 0,
       "Uluru is a sacred site for the Anangu people."),
    _q("aus-e-03", "Australia", "easy", "Which iconic bridge spans Sydney Harbour?",
       ["Story Bridge", "Sydney Harbour Bridge", "West Gate Bridge", "ANZAC Bridge"], 1,
       "Opened in 1932, affectionately called 'the Coathanger'."),
    _q("aus-e-04", "Australia", "easy", "What colour are the centres of a Lamington?",
       ["Sponge cake", "Pavlova", "Custard", "Jam"], 0,
       "A classic Aussie lamington is sponge cake dipped in chocolate and coconut."),
    _q("aus-e-05", "Australia", "easy", "Which Australian animal carries its baby in a pouch?",
       ["Wombat", "Echidna", "Kangaroo", "Dingo"], 2,
       "Kangaroos are marsupials — their joeys grow in the pouch."),
    _q("aus-e-06", "Australia", "easy", "What colour is the Australian opal famously known for?",
       ["Black", "Rainbow play of colour", "Pure white", "Blood red"], 1,
       "Opal shows a 'play of colour' caused by silica spheres."),

    _q("aus-m-01", "Australia", "moderate", "In what year did Australia adopt the metric system?",
       ["1966", "1970", "1974", "1980"], 2,
       "Australia switched from imperial to metric in 1974."),
    _q("aus-m-02", "Australia", "moderate", "Which Australian state has the largest land area?",
       ["Queensland", "New South Wales", "Western Australia", "South Australia"], 2,
       "WA covers roughly a third of the continent."),
    _q("aus-m-03", "Australia", "moderate", "Who wrote the novel 'Cloudstreet'?",
       ["Peter Carey", "Tim Winton", "Patrick White", "David Malouf"], 1,
       "Tim Winton's 1991 novel set in Perth."),
    _q("aus-m-04", "Australia", "moderate", "What is the floral emblem of Australia?",
       ["Waratah", "Banksia", "Golden Wattle", "Eucalyptus"], 2,
       "Acacia pycnantha, the Golden Wattle, was proclaimed in 1988."),
    _q("aus-m-05", "Australia", "moderate", "Which Australian PM disappeared while swimming in 1967?",
       ["Robert Menzies", "Harold Holt", "John Gorton", "Ben Chifley"], 1,
       "Harold Holt vanished at Cheviot Beach, Victoria."),
    _q("aus-m-06", "Australia", "moderate", "What is the meaning of the Aboriginal word 'Yarra'?",
       ["Flowing", "Sacred", "Mountain", "Sun"], 0,
       "The Yarra River name comes from a Wurundjeri word meaning 'flowing'."),

    _q("aus-h-01", "Australia", "hard", "Who was Australia's first Prime Minister?",
       ["Alfred Deakin", "Edmund Barton", "Andrew Fisher", "Joseph Cook"], 1,
       "Edmund Barton served 1901–1903."),
    _q("aus-h-02", "Australia", "hard", "In which year did Aboriginal Australians gain the constitutional right to be counted in the census?",
       ["1962", "1965", "1967", "1972"], 2,
       "The 1967 referendum amended the Constitution by over 90% support."),
    _q("aus-h-03", "Australia", "hard", "Which Australian invented the wine cask (goon bag)?",
       ["Tom Angove", "Penfold Grant", "Roger David", "Wolf Blass"], 0,
       "Thomas Angove patented the bag-in-box wine cask in 1965."),
    _q("aus-h-04", "Australia", "hard", "What was the name of the first European explorer to circumnavigate Australia?",
       ["James Cook", "Abel Tasman", "Matthew Flinders", "William Dampier"], 2,
       "Matthew Flinders did so in 1801–1803 aboard HMS Investigator."),
    _q("aus-h-05", "Australia", "hard", "Which mountain range runs along Australia's east coast?",
       ["MacDonnell Ranges", "Great Dividing Range", "Flinders Ranges", "Snowy Mountains"], 1,
       "The Great Dividing Range is over 3,500 km long."),

    _q("aus-n-01", "Australia", "nightmare", "Which Australian state was originally called Van Diemen's Land?",
       ["South Australia", "Tasmania", "Victoria", "Western Australia"], 1,
       "Renamed Tasmania in 1856 after the explorer Abel Tasman."),
    _q("aus-n-02", "Australia", "nightmare", "What is the highest mountain on the Australian mainland?",
       ["Mount Bogong", "Mount Kosciuszko", "Mount Townsend", "Mount Ossa"], 1,
       "Mt Kosciuszko, 2,228 m, in the Snowy Mountains."),
    _q("aus-n-03", "Australia", "nightmare", "In what year did Tasmania become a state of the Commonwealth?",
       ["1856", "1901", "1825", "1888"], 1,
       "All six colonies federated in 1901."),
    _q("aus-n-04", "Australia", "nightmare", "Which Australian scientists won the 2005 Nobel Prize in Medicine?",
       ["Robin Warren and Barry Marshall", "John Cornforth and Peter Doherty", "John Eccles and Macfarlane Burnet", "Howard Florey and Peter Doherty"], 0,
       "For showing H. pylori bacteria cause stomach ulcers."),

    # ---------------------------- HISTORY ----------------------------
    _q("his-e-01", "History", "easy", "In which year did World War II end?",
       ["1942", "1944", "1945", "1946"], 2,
       "WWII ended in 1945 with Japan's surrender in September."),
    _q("his-e-02", "History", "easy", "Who was the first person to walk on the Moon?",
       ["Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin", "John Glenn"], 1,
       "Apollo 11, 20 July 1969."),
    _q("his-e-03", "History", "easy", "Which wall came down in 1989?",
       ["Great Wall of China", "Hadrian's Wall", "Berlin Wall", "Wailing Wall"], 2,
       "The Berlin Wall fell on 9 November 1989."),
    _q("his-e-04", "History", "easy", "Who was the British monarch during most of WWII?",
       ["George V", "Edward VIII", "George VI", "Elizabeth II"], 2,
       "George VI reigned 1936–1952."),
    _q("his-e-05", "History", "easy", "Which ancient civilisation built the pyramids at Giza?",
       ["Greek", "Roman", "Egyptian", "Persian"], 2,
       "Built around 2,500 BC during the Old Kingdom."),
    _q("his-e-06", "History", "easy", "Who painted the Mona Lisa?",
       ["Michelangelo", "Leonardo da Vinci", "Raphael", "Caravaggio"], 1,
       "Leonardo painted her circa 1503–1519."),

    _q("his-m-01", "History", "moderate", "Which queen ruled England the longest?",
       ["Victoria", "Elizabeth I", "Elizabeth II", "Anne"], 2,
       "Elizabeth II reigned over 70 years (1952–2022)."),
    _q("his-m-02", "History", "moderate", "What year was the Great Fire of London?",
       ["1605", "1666", "1701", "1745"], 1,
       "The fire raged 2–5 September 1666."),
    _q("his-m-03", "History", "moderate", "Who was the first President of the United States?",
       ["Thomas Jefferson", "John Adams", "George Washington", "Benjamin Franklin"], 2,
       "Inaugurated 30 April 1789."),
    _q("his-m-04", "History", "moderate", "What was the name of the ship that brought the Pilgrims to America in 1620?",
       ["Santa Maria", "Mayflower", "Endeavour", "Discovery"], 1,
       "The Mayflower landed at Plymouth Rock."),
    _q("his-m-05", "History", "moderate", "The Cold War was primarily between which two countries?",
       ["USA and China", "UK and Russia", "USA and USSR", "Germany and Russia"], 2,
       "1947 to roughly 1991."),
    _q("his-m-06", "History", "moderate", "Which war was fought between 1914 and 1918?",
       ["The Boer War", "World War I", "The Crimean War", "The Spanish-American War"], 1,
       "Also called the Great War."),

    _q("his-h-01", "History", "hard", "In which year did the Titanic sink?",
       ["1910", "1912", "1914", "1916"], 1,
       "15 April 1912 in the North Atlantic."),
    _q("his-h-02", "History", "hard", "Who was the longest-serving British Prime Minister?",
       ["Winston Churchill", "William Gladstone", "Robert Walpole", "Margaret Thatcher"], 2,
       "Robert Walpole served 1721–1742 (~21 years)."),
    _q("his-h-03", "History", "hard", "What language did the ancient Romans speak?",
       ["Greek", "Latin", "Etruscan", "Sanskrit"], 1,
       "Classical Latin was the language of Rome."),
    _q("his-h-04", "History", "hard", "Which empire was ruled by Genghis Khan?",
       ["Persian", "Mongol", "Ottoman", "Roman"], 1,
       "He founded the Mongol Empire in 1206."),
    _q("his-h-05", "History", "hard", "The Treaty of Versailles formally ended which war?",
       ["WWI", "WWII", "Franco-Prussian War", "Napoleonic Wars"], 0,
       "Signed 28 June 1919."),

    _q("his-n-01", "History", "nightmare", "Who painted the ceiling of the Sistine Chapel?",
       ["Leonardo da Vinci", "Raphael", "Michelangelo", "Donatello"], 2,
       "Michelangelo painted it between 1508 and 1512."),
    _q("his-n-02", "History", "nightmare", "Who was the last Tsar of Russia?",
       ["Alexander III", "Nicholas II", "Peter III", "Paul I"], 1,
       "Nicholas II was executed in 1918."),
    _q("his-n-03", "History", "nightmare", "Which civilisation built Machu Picchu?",
       ["Aztec", "Maya", "Inca", "Olmec"], 2,
       "Built ~1450 in the Peruvian Andes."),
    _q("his-n-04", "History", "nightmare", "What year was the Magna Carta signed?",
       ["1066", "1215", "1314", "1453"], 1,
       "Sealed by King John at Runnymede in 1215."),

    # ---------------------------- MUSIC ----------------------------
    _q("mus-e-01", "Music", "easy", "Which band sang 'Hey Jude'?",
       ["The Rolling Stones", "The Beatles", "Queen", "ABBA"], 1,
       "Released by The Beatles in 1968."),
    _q("mus-e-02", "Music", "easy", "Who is known as the 'King of Rock and Roll'?",
       ["Chuck Berry", "Elvis Presley", "Little Richard", "Buddy Holly"], 1,
       "Elvis Presley earned the title in the 1950s."),
    _q("mus-e-03", "Music", "easy", "How many strings does a standard guitar have?",
       ["4", "5", "6", "7"], 2,
       "Six strings is standard for acoustic and electric guitars."),
    _q("mus-e-04", "Music", "easy", "Which Swedish group sang 'Dancing Queen'?",
       ["ABBA", "Ace of Base", "Roxette", "The Cardigans"], 0,
       "ABBA released the song in 1976."),
    _q("mus-e-05", "Music", "easy", "What instrument does a pianist play?",
       ["Violin", "Piano", "Flute", "Drums"], 1,
       "A pianist plays the piano."),
    _q("mus-e-06", "Music", "easy", "Which Queen song begins 'Is this the real life'?",
       ["Don't Stop Me Now", "Bohemian Rhapsody", "Somebody to Love", "Killer Queen"], 1,
       "Bohemian Rhapsody (1975) — written by Freddie Mercury."),

    _q("mus-m-01", "Music", "moderate", "Who is the 'Queen of Soul'?",
       ["Aretha Franklin", "Tina Turner", "Whitney Houston", "Diana Ross"], 0,
       "Aretha Franklin earned the title in the 1960s."),
    _q("mus-m-02", "Music", "moderate", "What instrument did Louis Armstrong play?",
       ["Saxophone", "Trumpet", "Piano", "Clarinet"], 1,
       "Satchmo was a virtuoso trumpeter and vocalist."),
    _q("mus-m-03", "Music", "moderate", "Which Beach Boys album includes 'Good Vibrations'?",
       ["Pet Sounds", "Smiley Smile", "Surfin' USA", "Holland"], 1,
       "'Good Vibrations' was originally on Smiley Smile (1967)."),
    _q("mus-m-04", "Music", "moderate", "Who sang 'I Will Always Love You' in the film 'The Bodyguard'?",
       ["Mariah Carey", "Celine Dion", "Whitney Houston", "Toni Braxton"], 2,
       "Whitney's 1992 cover topped charts worldwide."),
    _q("mus-m-05", "Music", "moderate", "Which composer was deaf?",
       ["Mozart", "Beethoven", "Brahms", "Schubert"], 1,
       "Beethoven was profoundly deaf by his late thirties."),
    _q("mus-m-06", "Music", "moderate", "Who sang the original 'Wind Beneath My Wings'?",
       ["Bette Midler", "Barbra Streisand", "Linda Ronstadt", "Sheena Easton"], 0,
       "From the 1988 film Beaches."),

    _q("mus-h-01", "Music", "hard", "In what city was The Beatles' first regular paid residency?",
       ["London", "Hamburg", "Liverpool", "New York"], 1,
       "They cut their teeth in Hamburg clubs in 1960–62."),
    _q("mus-h-02", "Music", "hard", "Which 1971 album by Carole King became a landmark of singer-songwriter pop?",
       ["Blue", "Tapestry", "Imagine", "Pearl"], 1,
       "Tapestry sold over 25 million copies worldwide."),
    _q("mus-h-03", "Music", "hard", "Who composed 'Rhapsody in Blue'?",
       ["George Gershwin", "Cole Porter", "Aaron Copland", "Leonard Bernstein"], 0,
       "Premiered in 1924."),
    _q("mus-h-04", "Music", "hard", "Which singer was known as the 'Black Madonna' of jazz?",
       ["Sarah Vaughan", "Billie Holiday", "Ella Fitzgerald", "Nina Simone"], 1,
       "Billie Holiday — that nickname celebrated her stage presence."),
    _q("mus-h-05", "Music", "hard", "Which instrument did jazz great Charlie Parker play?",
       ["Trumpet", "Alto saxophone", "Tenor saxophone", "Piano"], 1,
       "Parker pioneered bebop on alto sax."),

    _q("mus-n-01", "Music", "nightmare", "Who composed 'The Four Seasons'?",
       ["Bach", "Mozart", "Vivaldi", "Handel"], 2,
       "Antonio Vivaldi, published 1725."),
    _q("mus-n-02", "Music", "nightmare", "What is the highest female singing voice?",
       ["Soprano", "Mezzo-soprano", "Alto", "Contralto"], 0,
       "Soprano sits highest in the female range."),
    _q("mus-n-03", "Music", "nightmare", "Who wrote the libretto of Mozart's 'The Marriage of Figaro'?",
       ["Lorenzo Da Ponte", "Pietro Metastasio", "Emanuel Schikaneder", "Carlo Goldoni"], 0,
       "Lorenzo Da Ponte — a long-time Mozart collaborator."),
    _q("mus-n-04", "Music", "nightmare", "What is the German word for the song-cycle form Schubert popularised?",
       ["Lied", "Singspiel", "Volkslied", "Liederkreis"], 3,
       "A Liederkreis is a cycle of art songs."),

    # ---------------------------- MOVIES ----------------------------
    _q("mov-e-01", "Movies", "easy", "In which film does Julie Andrews sing 'Do-Re-Mi'?",
       ["Mary Poppins", "The Sound of Music", "My Fair Lady", "Annie"], 1,
       "The Sound of Music (1965)."),
    _q("mov-e-02", "Movies", "easy", "Which film features the line 'Here's looking at you, kid'?",
       ["Gone with the Wind", "Casablanca", "Citizen Kane", "The African Queen"], 1,
       "Humphrey Bogart in Casablanca (1942)."),
    _q("mov-e-03", "Movies", "easy", "Who played Indiana Jones?",
       ["Mel Gibson", "Harrison Ford", "Tom Selleck", "Roger Moore"], 1,
       "Harrison Ford starred from 1981 onwards."),
    _q("mov-e-04", "Movies", "easy", "Which film is set on the RMS Titanic?",
       ["Pearl Harbor", "Titanic", "The Poseidon Adventure", "Master and Commander"], 1,
       "James Cameron's 1997 blockbuster."),
    _q("mov-e-05", "Movies", "easy", "Who directed 'Jaws' and 'E.T.'?",
       ["Martin Scorsese", "George Lucas", "Steven Spielberg", "Francis Ford Coppola"], 2,
       "Both directed by Steven Spielberg."),
    _q("mov-e-06", "Movies", "easy", "Which Aussie actor starred in 'Crocodile Dundee'?",
       ["Mel Gibson", "Paul Hogan", "Bryan Brown", "Russell Crowe"], 1,
       "Paul Hogan co-wrote and starred."),

    _q("mov-m-01", "Movies", "moderate", "Who won Best Actor for 'Forrest Gump' (1994)?",
       ["Tom Cruise", "Tom Hanks", "Kevin Costner", "Michael Douglas"], 1,
       "Tom Hanks won his second consecutive Oscar."),
    _q("mov-m-02", "Movies", "moderate", "Which actress starred in 'Breakfast at Tiffany's'?",
       ["Grace Kelly", "Marilyn Monroe", "Audrey Hepburn", "Sophia Loren"], 2,
       "Audrey Hepburn as Holly Golightly (1961)."),
    _q("mov-m-03", "Movies", "moderate", "Who directed 'Vertigo' and 'Psycho'?",
       ["Alfred Hitchcock", "Orson Welles", "Billy Wilder", "John Ford"], 0,
       "Alfred Hitchcock — the Master of Suspense."),
    _q("mov-m-04", "Movies", "moderate", "What was the name of the cat in 'Breakfast at Tiffany's'?",
       ["Cat", "Holly", "Whiskers", "Tiffany"], 0,
       "He's literally named 'Cat'."),
    _q("mov-m-05", "Movies", "moderate", "Which film features 'I'll be back'?",
       ["Predator", "The Terminator", "Total Recall", "Commando"], 1,
       "Arnold Schwarzenegger in The Terminator (1984)."),
    _q("mov-m-06", "Movies", "moderate", "Who played Atticus Finch in 'To Kill a Mockingbird'?",
       ["Henry Fonda", "Gregory Peck", "James Stewart", "Spencer Tracy"], 1,
       "Gregory Peck won Best Actor (1962)."),

    _q("mov-h-01", "Movies", "hard", "Which film won Best Picture at the Oscars in 1972?",
       ["The Godfather", "Cabaret", "Deliverance", "Sleuth"], 0,
       "The Godfather won three Academy Awards that year."),
    _q("mov-h-02", "Movies", "hard", "Who directed 'Lawrence of Arabia'?",
       ["John Huston", "David Lean", "Stanley Kubrick", "Orson Welles"], 1,
       "David Lean's 1962 epic won 7 Oscars."),
    _q("mov-h-03", "Movies", "hard", "Which actress has won the most Best Actress Oscars?",
       ["Meryl Streep", "Katharine Hepburn", "Bette Davis", "Frances McDormand"], 1,
       "Katharine Hepburn won four times."),
    _q("mov-h-04", "Movies", "hard", "Who wrote the screenplay for 'Chinatown' (1974)?",
       ["Robert Towne", "William Goldman", "Paul Schrader", "Francis Ford Coppola"], 0,
       "Robert Towne — and it's considered a masterclass."),
    _q("mov-h-05", "Movies", "hard", "What was the first feature-length animated film by Walt Disney?",
       ["Pinocchio", "Snow White and the Seven Dwarfs", "Fantasia", "Bambi"], 1,
       "Released in 1937."),

    _q("mov-n-01", "Movies", "nightmare", "Who composed the music for 'Star Wars'?",
       ["Hans Zimmer", "Ennio Morricone", "John Williams", "James Horner"], 2,
       "John Williams composed the iconic 1977 score."),
    _q("mov-n-02", "Movies", "nightmare", "Which film won the first Best Picture Oscar?",
       ["Wings", "Sunrise", "The Jazz Singer", "Metropolis"], 0,
       "Wings won at the inaugural 1929 ceremony."),
    _q("mov-n-03", "Movies", "nightmare", "Who directed 'The Seventh Seal'?",
       ["Federico Fellini", "Ingmar Bergman", "Akira Kurosawa", "François Truffaut"], 1,
       "Ingmar Bergman's 1957 Swedish classic."),
    _q("mov-n-04", "Movies", "nightmare", "In what year did 'Citizen Kane' premiere?",
       ["1937", "1939", "1941", "1944"], 2,
       "Orson Welles' debut, 1 May 1941."),

    # ---------------------------- SPORT ----------------------------
    _q("spo-e-01", "Sport", "easy", "How many players are on a cricket team on the field?",
       ["9", "10", "11", "12"], 2,
       "Each team fields 11 players."),
    _q("spo-e-02", "Sport", "easy", "In tennis, what is a score of zero called?",
       ["Nil", "Love", "Duck", "Zip"], 1,
       "'Love' is thought to come from the French 'l'œuf' (the egg)."),
    _q("spo-e-03", "Sport", "easy", "Where were the 2000 Summer Olympic Games held?",
       ["Atlanta", "Sydney", "Athens", "Beijing"], 1,
       "Sydney hosted the Games of the XXVII Olympiad."),
    _q("spo-e-04", "Sport", "easy", "How long is a marathon (in kilometres, rounded)?",
       ["32 km", "38 km", "42 km", "50 km"], 2,
       "42.195 km — about 26.2 miles."),
    _q("spo-e-05", "Sport", "easy", "Which sport uses a 'shuttlecock'?",
       ["Squash", "Badminton", "Lacrosse", "Pickleball"], 1,
       "Badminton — shuttlecocks are sometimes called 'birdies'."),
    _q("spo-e-06", "Sport", "easy", "In which sport would you 'putt'?",
       ["Cricket", "Golf", "Bowls", "Snooker"], 1,
       "Putting is the gentle stroke used on the green."),

    _q("spo-m-01", "Sport", "moderate", "Who is the only batsman to have averaged over 99 in Test cricket?",
       ["Don Bradman", "Sachin Tendulkar", "Brian Lara", "Steve Smith"], 0,
       "Bradman finished his career at 99.94."),
    _q("spo-m-02", "Sport", "moderate", "How many holes are played in a regulation round of golf?",
       ["9", "12", "18", "21"], 2,
       "Eighteen holes per round."),
    _q("spo-m-03", "Sport", "moderate", "Which country has won the most FIFA World Cups (men's)?",
       ["Germany", "Italy", "Argentina", "Brazil"], 3,
       "Brazil has 5 titles."),
    _q("spo-m-04", "Sport", "moderate", "Who won the 1981 Ashes 'Botham's Ashes' series?",
       ["Australia", "England", "Drawn", "West Indies"], 1,
       "England won 3–1 after Ian Botham's heroics."),
    _q("spo-m-05", "Sport", "moderate", "Which boxer was famously called 'The Greatest'?",
       ["Mike Tyson", "Joe Frazier", "Muhammad Ali", "Sugar Ray Leonard"], 2,
       "Muhammad Ali coined the title himself."),
    _q("spo-m-06", "Sport", "moderate", "What colour jersey does the leader of the Tour de France wear?",
       ["Green", "Yellow", "Red", "Polka dot"], 1,
       "Le Maillot Jaune since 1919."),

    _q("spo-h-01", "Sport", "hard", "How long is an AFL quarter in minutes of play (excluding stoppages)?",
       ["15", "20", "22", "25"], 1,
       "AFL quarters are 20 minutes of playing time."),
    _q("spo-h-02", "Sport", "hard", "Which jockey rode Phar Lap to win the 1930 Melbourne Cup?",
       ["Jim Pike", "Bobbie Lewis", "Roy Higgins", "Harry White"], 0,
       "Jim Pike was Phar Lap's regular jockey."),
    _q("spo-h-03", "Sport", "hard", "How many points is a try worth in Rugby Union?",
       ["3", "4", "5", "6"], 2,
       "A try is worth 5 points (since 1992)."),
    _q("spo-h-04", "Sport", "hard", "Who was the first person to run a sub-4-minute mile?",
       ["Herb Elliott", "Roger Bannister", "Steve Ovett", "John Landy"], 1,
       "Roger Bannister, 6 May 1954, at Oxford."),
    _q("spo-h-05", "Sport", "hard", "In which year did the Sydney Swans win their first AFL premiership?",
       ["2001", "2005", "2012", "2016"], 1,
       "Sydney won in 2005, ending a 72-year drought."),

    _q("spo-n-01", "Sport", "nightmare", "Who has the most career singles Grand Slam titles in men's tennis (as of 2024)?",
       ["Roger Federer", "Rafael Nadal", "Novak Djokovic", "Pete Sampras"], 2,
       "Djokovic surpassed Nadal in 2023."),
    _q("spo-n-02", "Sport", "nightmare", "Which country won the first FIFA World Cup in 1930?",
       ["Brazil", "Argentina", "Uruguay", "Italy"], 2,
       "Uruguay hosted and won."),
    _q("spo-n-03", "Sport", "nightmare", "In rowing, what does 'stroke' mean?",
       ["The cox", "The rower at the stern who sets the rhythm", "The bow rower", "Any oar movement"], 1,
       "Stroke sits closest to the stern and sets tempo."),
    _q("spo-n-04", "Sport", "nightmare", "Who scored the 'Hand of God' goal in 1986?",
       ["Pele", "Maradona", "Romario", "Lineker"], 1,
       "Diego Maradona against England in the World Cup quarter-final."),

    # ---------------------------- GARDENING ----------------------------
    _q("gar-e-01", "Gardening", "easy", "Which insect helps pollinate most flowers?",
       ["Mosquito", "Bee", "Ant", "Fly"], 1,
       "Bees are the most important pollinators of flowering plants."),
    _q("gar-e-02", "Gardening", "easy", "What do you call decomposed organic matter used to enrich soil?",
       ["Mulch", "Compost", "Fertiliser", "Loam"], 1,
       "Compost is decomposed organic matter."),
    _q("gar-e-03", "Gardening", "easy", "Which plant is famous for its red 'flowers' on Christmas Day in the southern hemisphere?",
       ["Wisteria", "Bottlebrush", "Hibiscus", "Frangipani"], 1,
       "The Australian Callistemon (bottlebrush) blooms in summer."),
    _q("gar-e-04", "Gardening", "easy", "Which vegetable is famously associated with Popeye?",
       ["Lettuce", "Cabbage", "Spinach", "Broccoli"], 2,
       "Spinach gave Popeye his super strength."),
    _q("gar-e-05", "Gardening", "easy", "What does 'deadheading' mean?",
       ["Removing faded flowers", "Repotting", "Hard pruning", "Watering at dawn"], 0,
       "It encourages more blooms."),
    _q("gar-e-06", "Gardening", "easy", "What's the main ingredient in 'Sunday roast' carrots?",
       ["Beetroot", "Carrots", "Parsnips", "Turnips"], 1,
       "Carrots, of course!"),

    _q("gar-m-01", "Gardening", "moderate", "Which plant family do tomatoes belong to?",
       ["Cucurbitaceae", "Solanaceae", "Brassicaceae", "Rosaceae"], 1,
       "Tomatoes are in the nightshade family, Solanaceae."),
    _q("gar-m-02", "Gardening", "moderate", "Which Australian native is famous for its grass-tree-like flower spike?",
       ["Wattle", "Banksia", "Grass tree (Xanthorrhoea)", "Lilly pilly"], 2,
       "Xanthorrhoea sends up a striking flower spike after rain or fire."),
    _q("gar-m-03", "Gardening", "moderate", "What is the optimal soil pH for most vegetables?",
       ["4.0–5.0", "5.5–6.5", "7.5–8.5", "8.5–9.5"], 1,
       "Most veg prefer slightly acidic, around 6–6.5."),
    _q("gar-m-04", "Gardening", "moderate", "Which flower has varieties like 'Iceberg' and 'Peace'?",
       ["Camellia", "Rose", "Hydrangea", "Dahlia"], 1,
       "Both 'Iceberg' and 'Peace' are famous rose cultivars."),
    _q("gar-m-05", "Gardening", "moderate", "Which kitchen staple deters slugs from a garden bed?",
       ["Sugar", "Crushed eggshells", "Olive oil", "Vinegar"], 1,
       "Sharp eggshells form a tactile barrier."),
    _q("gar-m-06", "Gardening", "moderate", "What does 'companion planting' mean?",
       ["Planting trees together", "Pairing plants for mutual benefit", "Growing only one species", "Planting in rows"], 1,
       "Like basil near tomatoes, or marigolds near vegetables."),

    _q("gar-h-01", "Gardening", "hard", "What soil pH do blueberries prefer?",
       ["3.5–4.5 (very acidic)", "5.5–6.5 (slightly acidic)", "6.5–7.5 (neutral)", "8.0+ (alkaline)"], 0,
       "Blueberries thrive in very acidic soils."),
    _q("gar-h-02", "Gardening", "hard", "What kind of plant is a fuchsia?",
       ["Annual herb", "Perennial shrub", "Bulb", "Climber only"], 1,
       "Fuchsias are perennial shrubs (some climb)."),
    _q("gar-h-03", "Gardening", "hard", "Which nutrient promotes leafy growth in plants?",
       ["Nitrogen", "Phosphorus", "Potassium", "Calcium"], 0,
       "N is the leaf-and-stem builder."),
    _q("gar-h-04", "Gardening", "hard", "Which famous English garden was designed by Vita Sackville-West?",
       ["Hidcote", "Sissinghurst", "Great Dixter", "Wisley"], 1,
       "Sissinghurst Castle Garden, Kent."),
    _q("gar-h-05", "Gardening", "hard", "What is the name of the Italian style of formal garden featuring parterres and statuary?",
       ["Giardino segreto", "Giardino all'italiana", "Pleasure garden", "Cottage garden"], 1,
       "Giardino all'italiana — Italian Renaissance gardens."),

    _q("gar-n-01", "Gardening", "nightmare", "What does 'F1 hybrid' mean on a seed packet?",
       ["First-generation cross of two pure lines", "Fully organic line", "Frost-tolerant variety", "Genetically modified"], 0,
       "F1 = first filial generation, offspring of two distinct parent lines."),
    _q("gar-n-02", "Gardening", "nightmare", "Which plant hormone primarily controls fruit ripening?",
       ["Auxin", "Gibberellin", "Ethylene", "Cytokinin"], 2,
       "Ethylene gas triggers ripening — why bananas ripen others in the bowl."),
    _q("gar-n-03", "Gardening", "nightmare", "What does 'chitting' potatoes mean?",
       ["Pre-sprouting before planting", "Earthing up", "Curing after harvest", "Cutting seed potatoes"], 0,
       "You stand seed potatoes in light to encourage shoots."),
    _q("gar-n-04", "Gardening", "nightmare", "Which scientific term describes plants that complete their life cycle in two years?",
       ["Annual", "Biennial", "Perennial", "Ephemeral"], 1,
       "Biennials like foxgloves and parsley take two seasons."),

    # ---------------------------- GENERAL KNOWLEDGE ----------------------------
    _q("gen-e-01", "General Knowledge", "easy", "How many continents are there?",
       ["5", "6", "7", "8"], 2,
       "Most geographers count seven continents."),
    _q("gen-e-02", "General Knowledge", "easy", "What gas do plants absorb from the air?",
       ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], 2,
       "Plants take in CO₂ for photosynthesis and release oxygen."),
    _q("gen-e-03", "General Knowledge", "easy", "How many days are in a leap year?",
       ["364", "365", "366", "367"], 2,
       "366 days — February gets the extra day."),
    _q("gen-e-04", "General Knowledge", "easy", "What is the largest ocean on Earth?",
       ["Atlantic", "Indian", "Arctic", "Pacific"], 3,
       "The Pacific covers about a third of the planet."),
    _q("gen-e-05", "General Knowledge", "easy", "Which planet is known as the Red Planet?",
       ["Venus", "Mars", "Jupiter", "Saturn"], 1,
       "Mars looks red due to iron oxide on its surface."),
    _q("gen-e-06", "General Knowledge", "easy", "What is H₂O more commonly known as?",
       ["Salt", "Sugar", "Water", "Vinegar"], 2,
       "H₂O is the chemical formula for water."),

    _q("gen-m-01", "General Knowledge", "moderate", "Which element has the chemical symbol 'Au'?",
       ["Silver", "Gold", "Aluminium", "Argon"], 1,
       "Au comes from the Latin 'aurum'."),
    _q("gen-m-02", "General Knowledge", "moderate", "What is the smallest country in the world?",
       ["Monaco", "San Marino", "Vatican City", "Liechtenstein"], 2,
       "Vatican City — about 49 hectares."),
    _q("gen-m-03", "General Knowledge", "moderate", "How many primary colours are there in painting?",
       ["2", "3", "4", "5"], 1,
       "Red, yellow and blue — the painter's primaries."),
    _q("gen-m-04", "General Knowledge", "moderate", "What is the currency of Japan?",
       ["Won", "Yuan", "Yen", "Ringgit"], 2,
       "Japanese Yen — symbol ¥."),
    _q("gen-m-05", "General Knowledge", "moderate", "Which is the largest mammal on Earth?",
       ["African elephant", "Blue whale", "Sperm whale", "Giraffe"], 1,
       "Blue whales can reach 30+ metres long."),
    _q("gen-m-06", "General Knowledge", "moderate", "What language has the most native speakers?",
       ["English", "Hindi", "Mandarin Chinese", "Spanish"], 2,
       "Around 900 million native Mandarin speakers."),

    _q("gen-h-01", "General Knowledge", "hard", "How many bones are in the adult human body?",
       ["196", "206", "216", "226"], 1,
       "An adult skeleton has 206 bones."),
    _q("gen-h-02", "General Knowledge", "hard", "What is the tallest mountain in the world (above sea level)?",
       ["K2", "Kangchenjunga", "Mount Everest", "Mauna Kea"], 2,
       "Everest at 8,849 m above sea level."),
    _q("gen-h-03", "General Knowledge", "hard", "Which country gifted the Statue of Liberty to the United States?",
       ["United Kingdom", "France", "Italy", "Spain"], 1,
       "A gift from France in 1886."),
    _q("gen-h-04", "General Knowledge", "hard", "Which is the largest desert in the world?",
       ["Sahara", "Gobi", "Antarctic", "Arabian"], 2,
       "Antarctica is technically the largest 'cold' desert."),
    _q("gen-h-05", "General Knowledge", "hard", "What is the hardest natural substance on Earth?",
       ["Quartz", "Diamond", "Titanium", "Granite"], 1,
       "Diamond — 10 on the Mohs scale."),

    _q("gen-n-01", "General Knowledge", "nightmare", "What is the longest river in the world?",
       ["Amazon", "Nile", "Yangtze", "Mississippi"], 1,
       "At ~6,650 km, the Nile is generally considered the longest."),
    _q("gen-n-02", "General Knowledge", "nightmare", "Who is credited with inventing the telephone?",
       ["Thomas Edison", "Alexander Graham Bell", "Nikola Tesla", "Guglielmo Marconi"], 1,
       "Alexander Graham Bell, 1876."),
    _q("gen-n-03", "General Knowledge", "nightmare", "Which is the only US state to grow coffee commercially?",
       ["Florida", "California", "Hawaii", "Louisiana"], 2,
       "Kona coffee grows on the Big Island, Hawaii."),
    _q("gen-n-04", "General Knowledge", "nightmare", "How many time zones does Russia span?",
       ["9", "11", "13", "15"], 1,
       "Russia spans 11 time zones."),
]


# ---------- Helpers ----------
def category_counts():
    out: dict = {}
    for q in QUESTIONS:
        cat = q["category"]
        diff = q["difficulty"]
        out.setdefault(cat, {"easy": 0, "moderate": 0, "hard": 0, "nightmare": 0, "total": 0})
        out[cat][diff] = out[cat].get(diff, 0) + 1
        out[cat]["total"] = out[cat].get("total", 0) + 1
    return out


# Points awarded for completing a Trivia session.
DIFFICULTY_POINTS = {
    "easy": 5,
    "moderate": 10,
    "hard": 20,
    "nightmare": 35,
}

# Display labels & meta for the UI.
DIFFICULTY_META = [
    {"key": "easy",      "label": "Easy",      "icon": "leaf",          "color": "#0F766E", "points": 5,  "questions": 6},
    {"key": "moderate",  "label": "Moderate",  "icon": "sparkles",      "color": "#2563EB", "points": 10, "questions": 8},
    {"key": "hard",      "label": "Hard",      "icon": "flash",         "color": "#B45309", "points": 20, "questions": 10},
    {"key": "nightmare", "label": "Nightmare", "icon": "skull",         "color": "#7C3AED", "points": 35, "questions": 12},
]


def question_count_for(difficulty: str) -> int:
    for m in DIFFICULTY_META:
        if m["key"] == difficulty:
            return m["questions"]
    return 8
