"""Iter193 — Signup restructure + Notice Board fixes.
Backend verification of:
  1. Minimal signup (email + password) creates account (username auto-generated by frontend, but backend accepts unique username).
  2. POST /users/{id}/location accepts `hidden` flag while still storing suburb.
  3. Notice Board create → immediately visible in feed (even under category filter caveats).
"""
import os
import time
import uuid
import pytest
import requests

def _base_url():
    # Prefer /app/frontend/.env since conftest.py sets a stale default.
    try:
        with open("/app/frontend/.env") as f:
            for line in f:
                if line.startswith("EXPO_PUBLIC_BACKEND_URL="):
                    return line.split("=", 1)[1].strip().strip('"').rstrip("/")
    except Exception:
        pass
    return os.environ.get("EXPO_PUBLIC_BACKEND_URL", "").rstrip("/")


BASE_URL = _base_url()


@pytest.fixture(scope="module")
def api():
    s = requests.Session()
    s.headers.update({"Content-Type": "application/json"})
    return s


@pytest.fixture(scope="module")
def new_user(api):
    rand = uuid.uuid4().hex[:8]
    payload = {
        "username": f"qa{rand}",
        "password": "secret123",
        "email": f"qa+{rand}@example.com",
    }
    r = api.post(f"{BASE_URL}/api/auth/signup", json=payload, timeout=20)
    assert r.status_code == 200, f"signup failed: {r.status_code} {r.text}"
    data = r.json()
    assert "access_token" in data
    assert "user" in data
    u = data["user"]
    assert u.get("email") == payload["email"]
    return {"token": data["access_token"], "user": u}


class TestMinimalSignup:
    def test_signup_no_username_first_name_suburb_ok(self, new_user):
        """Frontend now sends only username(auto)+password+email; no first_name/suburb."""
        u = new_user["user"]
        assert u.get("id")
        # first_name/suburb should NOT be required to create the account
        # They may be empty/absent at this stage.
        assert not u.get("suburb")  # profile not complete yet


class TestLocationHiddenFlag:
    def test_set_location_hidden_stores_suburb(self, api, new_user):
        u = new_user["user"]
        headers = {"Authorization": f"Bearer {new_user['token']}"}
        payload = {
            "suburb": "Bondi",
            "postcode": "2026",
            "state": "NSW",
            "hidden": True,
        }
        r = api.post(f"{BASE_URL}/api/users/{u['id']}/location", json=payload, timeout=15)
        assert r.status_code == 200, f"set location failed: {r.status_code} {r.text}"
        # Fetch profile to verify suburb persisted even when hidden
        r2 = api.get(f"{BASE_URL}/api/users/{u['id']}", headers=headers, timeout=15)
        assert r2.status_code == 200
        prof = r2.json()
        assert prof.get("suburb") == "Bondi", f"suburb not persisted: {prof}"
        # hidden flag might surface as suburb_hidden or location_visibility
        hidden = prof.get("suburb_hidden") or prof.get("location_visibility") in ("hidden", "private")
        assert hidden, f"hidden flag not stored: {prof}"

    def test_unhide_keeps_suburb(self, api, new_user):
        u = new_user["user"]
        headers = {"Authorization": f"Bearer {new_user['token']}"}
        payload = {"suburb": "Bondi", "postcode": "2026", "state": "NSW", "hidden": False}
        r = api.post(f"{BASE_URL}/api/users/{u['id']}/location", json=payload, timeout=15)
        assert r.status_code == 200
        r2 = api.get(f"{BASE_URL}/api/users/{u['id']}", headers=headers, timeout=15)
        assert r2.status_code == 200
        prof = r2.json()
        assert prof.get("suburb") == "Bondi"


class TestNoticeCreateVisible:
    """Login as existing member and verify create → feed visibility."""

    @pytest.fixture(scope="class")
    def member(self, api):
        r = api.post(f"{BASE_URL}/api/auth/login",
                     json={"username": "member@friendplace.com.au", "password": "TestPass2026!"},
                     timeout=15)
        if r.status_code != 200:
            pytest.skip(f"member login failed {r.status_code}: {r.text}")
        return r.json()["user"]

    def test_create_notice_appears_in_feed_all_filter(self, api, member):
        payload = {
            "user_id": member["id"],
            "user_name": member.get("first_name") or member.get("username"),
            "avatar": member.get("avatar"),
            "title": f"TEST_notice_{uuid.uuid4().hex[:6]}",
            "body": "iter193 e2e notice",
            "category": "Announcement",
        }
        r = api.post(f"{BASE_URL}/api/notices", json=payload, timeout=20)
        assert r.status_code in (200, 201), f"create failed: {r.status_code} {r.text}"
        notice = r.json()
        assert notice.get("id")
        held = notice.get("held_for_review")
        # Now fetch feed with All filter
        r2 = api.get(f"{BASE_URL}/api/notices",
                     params={"user_id": member["id"], "category": "All", "radius_km": 5},
                     timeout=15)
        assert r2.status_code == 200
        feed = r2.json()
        found = any(x.get("id") == notice["id"] for x in feed)
        if held:
            # Held notices may or may not appear in the general feed
            pytest.skip("Notice held for review — pending-review path (acceptable)")
        assert found, f"created notice not in feed (n={len(feed)}); id={notice['id']}"

    def test_create_notice_under_category_filter(self, api, member):
        """Even when caller filters by a different category, the freshly-created
        notice's id must be retrievable via category=All."""
        payload = {
            "user_id": member["id"],
            "user_name": member.get("first_name") or member.get("username"),
            "avatar": member.get("avatar"),
            "title": f"TEST_qcat_{uuid.uuid4().hex[:6]}",
            "body": "posted while filter was Question",
            "category": "Community",
        }
        r = api.post(f"{BASE_URL}/api/notices", json=payload, timeout=20)
        assert r.status_code in (200, 201)
        n = r.json()
        if n.get("held_for_review"):
            pytest.skip("held for review")
        # Confirm findable via All
        r2 = api.get(f"{BASE_URL}/api/notices",
                     params={"user_id": member["id"], "category": "All", "radius_km": 5},
                     timeout=15)
        assert r2.status_code == 200
        assert any(x.get("id") == n["id"] for x in r2.json())
