import type { MetadataRoute } from 'next';

/**
 * Programmatic robots.txt — mirrors /public/robots.txt but is
 * generated by Next.js so we can flip it via an env var without
 * touching the file. Whichever Next.js finds first wins; the static
 * public/robots.txt is our belt-and-braces backup.
 */
export default function robots(): MetadataRoute.Robots {
  const indexable = process.env.FRIENDPLACE_INDEXABLE === 'true';
  return {
    rules: [{ userAgent: '*', ...(indexable ? { allow: '/' } : { disallow: '/' }) }],
  };
}
